In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [23]:
df=pd.read_csv("train.csv")
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [24]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

Dependent and Independent variable separated in different identities

In [25]:
target=df.Survived
inputs=df.drop('Survived',axis='columns')

In [26]:
dummies=pd.get_dummies(inputs.Sex).astype(int)
dummies.head(3)

   female  male
0       0     1
1       1     0
2       1     0

In [27]:
inputs=pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0

In [28]:
inputs.drop('Sex',axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0

In [29]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [30]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [31]:
inputs.Age=inputs.Age.fillna(inputs.Age.mean())
inputs.head(3)

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(inputs, target, test_size=0.2)

In [33]:
len(X_train)

712

In [34]:
len(X_test)

179

In [35]:
len(inputs)

891

In [36]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [37]:
model.fit(X_train,Y_train)

GaussianNB()

In [38]:
model.score(X_test,Y_test)

0.8268156424581006

In [39]:
X_test[:10]

     Pclass        Age     Fare  female  male
239       2  33.000000  12.2750       0     1
482       3  50.000000   8.0500       0     1
788       3   1.000000  20.5750       0     1
70        2  32.000000  10.5000       0     1
851       3  74.000000   7.7750       0     1
719       3  33.000000   7.7750       0     1
449       1  52.000000  30.5000       0     1
690       1  31.000000  57.0000       0     1
786       3  18.000000   7.4958       1     0
697       3  29.699118   7.7333       1     0

In [40]:
Y_test[:10]

239    0
482    0
788    1
70     0
851    0
719    0
449    1
690    1
786    1
697    1
Name: Survived, dtype: int64

In [41]:
model.predict(X_test[:10])

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [42]:
model.predict_proba(X_test[:10])

array([[0.97483615, 0.02516385],
       [0.98775044, 0.01224956],
       [0.97683696, 0.02316304],
       [0.97456692, 0.02543308],
       [0.97846055, 0.02153945],
       [0.98833503, 0.01166497],
       [0.89746338, 0.10253662],
       [0.8255343 , 0.1744657 ],
       [0.09214903, 0.90785097],
       [0.10798729, 0.89201271]])